### ISSUE TITLE
ERROR    Computed fully qualified role name of ansibleroleibmterrformprovider does not follow current galaxy requirements.

### ISSUE THREAD

**Issue by penguinperk** [penguinperk/ansible_role_ibm_terraform_provider#1]
2s
Run molecule test
INFO     default scenario test matrix: dependency, lint, cleanup, destroy, syntax, create, prepare, converge, idempotence, side_effect, verify, cleanup, destroy
INFO     Performing prerun...
INFO     Added ANSIBLE_LIBRARY=/home/runner/.cache/ansible-compat/f97b49/modules:/home/runner/.ansible/plugins/modules:/usr/share/ansible/plugins/modules
INFO     Added ANSIBLE_COLLECTIONS_PATH=/home/runner/.cache/ansible-compat/f97b49/collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
INFO     Added ANSIBLE_ROLES_PATH=/home/runner/.cache/ansible-compat/f97b49/roles:/home/runner/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
ERROR    Computed fully qualified role name of ansibleroleibmterrformprovider does not follow current galaxy requirements.
Please edit meta/main.yml and assure we can correctly determine full role name:

galaxy_info:
role_name: my_name  # if absent directory name hosting role is used instead
namespace: my_galaxy_namespace  # if absent, author is used instead

Namespace: https://galaxy.ansible.com/docs/contributing/namespaces.html#galaxy-namespace-limitations
Role: https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names

As an alternative, you can add 'role-name' to either skip_list or warn_list.

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.7/x64/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/molecule/command/test.py", line 159, in test
    base.execute_cmdline_scenarios(scenario_name, args, command_args, ansible_args)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/molecule/command/base.py", line 111, in execute_cmdline_scenarios
    scenario.config.runtime.prepare_environment()
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/ansible_compat/runtime.py", line 255, in prepare_environment
    self._install_galaxy_role(self.project_dir, ignore_errors=True)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/ansible_compat/runtime.py", line 396, in _install_galaxy_role
    raise InvalidPrerequisiteError(msg)
ansible_compat.errors.InvalidPrerequisiteError: Computed fully qualified role name of ansibleroleibmterrformprovider does not follow current galaxy requirements.
Please edit meta/main.yml and assure we can correctly determine full role name:

galaxy_info:
role_name: my_name  # if absent directory name hosting role is used instead
namespace: my_galaxy_namespace  # if absent, author is used instead

Namespace: https://galaxy.ansible.com/docs/contributing/namespaces.html#galaxy-namespace-limitations
Role: https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names

As an alternative, you can add 'role-name' to either skip_list or warn_list.

Error: Process completed with exit code 1.

**Comment by samdoran** [comment]
It looks like `molecule` is symlinking the source checkout to `.cache/roles/[namespace].[role_name]` and it's pulling those values from `meta/main.yml`. The `namespace` key is currently missing.

```patch
diff --git meta/main.yml meta/main.yml
index 03524a9..72b9903 100644
--- meta/main.yml
+++ meta/main.yml
@@ -1,6 +1,6 @@
 galaxy_info:
   role_name: ibm_terraform_provider
-  my_galaxy_namespace: penguinperk
+  namespace: penguinperk
   author: Scott Perkins
   description: Deploys the IBM Cloud Terraform Provider
   company: None
@@ -54,7 +54,7 @@ galaxy_info:
         - trusty
         - xenial
         - bionic
-  
+
   galaxy_tags: []
     # List tags for your role here, one per line. A tag is a keyword that describes
     # and categorizes the role. Users find roles by searching for tags. Be sure to

```

**Comment by penguinperk** [comment]
I re-ran molecule test locally and received:

TASK [include penguinperk.ibm_terraform_provider] ******************************
ERROR! the role 'ibm_terraform_provider' was not found in /Users/scott/Documents/src/ansible_role_ibm_terraform_provider/molecule/default/roles:/Users/scott/.cache/molecule/ansible_role_ibm_terraform_provider/default/roles:/Users/scott/Documents/src:/Users/scott/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/Users/scott/.cache/ansible-compat/d71b91/roles:/Users/scott/Documents/src/ansible_role_ibm_terraform_provider/roles:/etc/ansible/roles:/Users/scott/Documents/src/ansible_role_ibm_terraform_provider/molecule/default

The error appears to be in '/Users/scott/Documents/src/ansible_role_ibm_terraform_provider/molecule/default/converge.yml': line 7, column 15, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      include_role:
        name: "ibm_terraform_provider"
              ^ here
